(self.webpackChunk=self.webpackChunk||[]).push([[717],{66521:function(F,l,u){"use strict";u.r(l),u.d(l,{default:function(){return Z}});var p=u(27424),S=u.n(p),I=u(69792),g=u(62435),N=u(38416),A=u.n(N),P=function(n){switch(n.type){case"string":return"text";case"number":return"digit";case"boolean":return"select";case"unknown":return null;default:return null}},E=function(n){return n.map(function(e){var t={key:e.key,dataIndex:e.key,title:e.comment||e.key||""},o=P(e);return o&&(t.valueType=o),t})},k=function(n){var e=n.map(function(t){switch(t.type){case"string":return"<ProFormText name={'".concat(t.key,"'} label={'").concat(t.comment||t.key||"","'}/>");case"number":return"<ProFormDigit name={'".concat(t.key,"'} label={'").concat(t.comment||t.key||"","'}/>");case"boolean":return"<ProFormSelect name={'".concat(t.key,"'} label={'").concat(t.comment||t.key||"","'}/>");case"unknown":default:return"<ProFormText name={'".concat(t.key,"'} label={'").concat(t.comment||t.key||"","'}/>")}});return e.join(`
`)},d,s=function(a){return a[a.COLUMNS_ARRAY=0]="COLUMNS_ARRAY",a[a.PRO_FORM_ITEM=1]="PRO_FORM_ITEM",a}({}),C=(d={},A()(d,s.COLUMNS_ARRAY,{convertFn:E,enableJSONStringify:!0}),A()(d,s.PRO_FORM_ITEM,{convertFn:k}),d),j=[{value:s.COLUMNS_ARRAY,label:"=> ColumnsArray"},{value:s.PRO_FORM_ITEM,label:"=> ProFormItem"}],b=`type exampleType = {
    /**\u6211\u662F\u5B57\u6BB5\u6CE8\u91CA*/
    code?: string;
    name?: string;
    message?: string;
    success?: boolean;
    count?: number;
}
`,v=u(55423),h=u(96109),D=function(n){return n.kind===v.SyntaxKind.TypeAliasDeclaration},L=function(n){switch(n==null?void 0:n.kind){case v.SyntaxKind.StringKeyword:return"string";case v.SyntaxKind.NumberKeyword:return"number";case v.SyntaxKind.BooleanKeyword:return"boolean";default:return"unknown"}},B=function(n){var e;if(!n)return[];var t=(0,v.createSourceFile)("type.ts",n,v.ScriptTarget.Latest,!0).statements[0];if(!D(t))return h.ZP.error("\u975ETS\u7C7B\u578B\u5B9A\u4E49\u4EE3\u7801\uFF0C\u65E0\u6CD5\u8F6C\u6362\uFF0C\u8BF7\u68C0\u67E5"),[];var o=t==null||(e=t.type)===null||e===void 0?void 0:e.members;return Array.isArray(o)?o.map(function(r){var i,m,y;return{key:r==null||(i=r.name)===null||i===void 0?void 0:i.escapedText,type:L(r==null?void 0:r.type),comment:r==null||(m=r.jsDoc)===null||m===void 0||(y=m[0])===null||y===void 0?void 0:y.comment}}):(h.ZP.error("TS\u7C7B\u578B\u5B9A\u4E49\u5185\u5BB9\u4E3A\u7A7A\uFF0C\u65E0\u6CD5\u8F6C\u6362\uFF0C\u8BF7\u68C0\u67E5"),[])},K=function(n,e){var t;return(t=C[e])===null||t===void 0?void 0:t.convertFn(n)},R=function(n,e){var t=B(n),o=K(t,e);try{var r;return(r=C[e])!==null&&r!==void 0&&r.enableJSONStringify?JSON.stringify(o,null,2):o}catch(i){return h.ZP.error(i==null?void 0:i.toString()),""}},x=u(60874),O=u(533),c=u(86074);function Z(){var a=(0,g.useState)(b),n=S()(a,2),e=n[0],t=n[1],o=(0,g.useState)(""),r=S()(o,2),i=r[0],m=r[1],y=(0,g.useState)(s.COLUMNS_ARRAY),M=S()(y,2),U=M[0],Y=M[1],w=function(f){t(f)},$=function(){m(R(e,U))},J=function(f){Y(f),m(R(e,f))},V=function(){return(0,c.jsxs)("div",{children:[(0,c.jsx)("span",{children:"\u6620\u5C04\u6A21\u5F0F\u9009\u62E9\uFF1A"}),(0,c.jsx)(I.Z,{defaultValue:s.COLUMNS_ARRAY,onChange:J,options:j})]})};return(0,c.jsxs)(O.ZP,{children:[(0,c.jsx)(O.ZP,{title:"TS\u7C7B\u578B\u4EE3\u7801\u8F93\u5165\u533A\u57DF",onBlur:$,colSpan:"50%",children:(0,c.jsx)(x.Z,{width:"100%",height:700,language:"typescript",value:e,onChange:w,options:{selectOnLineNumbers:!0}},"input")}),(0,c.jsx)(O.ZP,{title:"\u6620\u5C04\u7ED3\u679C",extra:V(),children:(0,c.jsx)(x.Z,{width:"100%",height:700,value:i,options:{selectOnLineNumbers:!0}},"output")})]})}},13411:function(F){function l(u){var p=new Error("Cannot find module '"+u+"'");throw p.code="MODULE_NOT_FOUND",p}l.keys=function(){return[]},l.resolve=l,l.id=13411,F.exports=l},62183:function(){},13024:function(){},62715:function(){},13611:function(){},28353:function(){},1210:function(){},43454:function(){}}]);
